import Head from 'next/head'

export default function Home() {
  return (
    <div className="px-8">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="min-h-screen py-16 flex flex-col justify-center items-center">
        <h1 className="text-6xl font-bold">
          Welcome to <a className="text-blue-600 hover:underline" href="https://nextjs.org">Next.js!</a>
        </h1>
      </main>
    </div>
  )
}
